// <auto-generated />
using System;
using Aufgabe_EF1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aufgabe_EF1.Migrations
{
    [DbContext(typeof(BibliothekDb))]
    [Migration("20211029082011_BuchTabelle")]
    partial class BuchTabelle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aufgabe_EF1.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Autor_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Geburtsdatum")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("AutorID");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("Aufgabe_EF1.Buch", b =>
                {
                    b.Property<int>("BuchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Buch_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("Autor_ID");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("BuchID");

                    b.HasIndex("AutorId");

                    b.ToTable("Buch");
                });

            modelBuilder.Entity("Aufgabe_EF1.Buch", b =>
                {
                    b.HasOne("Aufgabe_EF1.Autor", "Autor")
                        .WithMany("Buch")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Aufgabe_EF1.Autor", b =>
                {
                    b.Navigation("Buch");
                });
#pragma warning restore 612, 618
        }
    }
}
